<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="title" content="AEC Library is a comprehensive library management system">
  <meta name="description"
    content="Designed for both large and small library systems, AEC Library is a comprehensive library management system. For managing circulation and stock, this is ideal for institutional, public, and digital libraries. In order to manage and automate the processing of even the largest of libraries, the AEC Library website was developed. According to the end user's requirements, the website is capable of managing Book Issues, Returns, and generating various Reports for Record-Keeping and Review purposes.">
  <meta name="keywords" content="AEC, library systems, library, digital libraries, books">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta name="language" content="English">
  <meta name="author" content="AEC LIBRARY">
  <link rel="icon" href="img/finalLogo.webp" type="image/x-icon" />
  <title>About | AEC Library</title>

  <!-- Bootstrap CSS webp-->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous" />
  <!-- Style CSS -->
  <link rel="stylesheet" href="assets/css/About.css" />

  <!-- Adding new font -> Playfair-display -->
  <link href="https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap" rel="stylesheet" />
  <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
  <!--Adding AOS in it-->
  <!-- <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script> -->

  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
</head>

<body class="body-style">


  <div id="topBtn" title="Go to Top">
    <a href="#"><span class="fa fa-angle-up"></span></a>
  </div>

  <!-- Navbar started -->
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-info">
      <a class="navbar-brand" href="index2.php"><img src="assets/logos/finalLogo.webp" alt="AEC Library"
          class="logo-img" /></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="index2.php"><i class="fas fa-home"></i> Acceuil<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link active" onclick="return false;">
              <i class="fas fa-book"></i> Qui Sommes-Nous?
            </a>
          </li>


          <li class="nav-item">
            <a href="public/login.php" class="nav-link">
              <i class="fas fa-sign-in-alt"></i> Se connecter
            </a>
          </li>
          <li class="nav-item">
            <a href="public/inscription.php" class="nav-link">
              <i class="fas fa-sign-in-alt"></i> Inscription
            </a>
          </li>
          <li class="nav-item">
            <a href="index2.php#propositions" class="nav-link">
              <i class="fas fa-address-book"></i> Propositions
            </a>
          </li>

        </ul>

      </div>
    </nav>
  </header>
  <!-- Navbar ended -->

  <!-- about content started -->
  <main class="about-container" data-aos="fade-up">
    <!-- <div class="my-5"> -->
    <div class="first">
      <h1 class="text-center">Qui Sommes-Nous?</h1>

      <div class="py-3 mx-md-5 mx-3 ">
        <p>
          Conçu pour les systèmes de bibliothèque de toutes tailles, AEC Library est un système de gestion de bibliothèque complet. Idéal pour la gestion des prêts et des stocks, il convient aux bibliothèques institutionnelles, publiques et numériques. Le site web AEC Library a été développé pour gérer et automatiser le traitement, même des plus grandes bibliothèques. En fonction des besoins des utilisateurs finaux, le site est capable de gérer les emprunts et retours de livres, ainsi que de générer divers rapports pour la tenue des dossiers et les revues.
        </p>
      </div>
    </div>
    <div class="first">
      <h2 class="text-white">
        <strong>Pourquoi utiliser AEC Library ?</strong>
      </h2>
      <p>
      Grâce à AEC Library, le processus de distribution est contrôlé et centralisé, ce qui réduit les risques de perte de livres, de surcommandes et de remplacements coûteux. AEC Library fournit des informations claires et détaillées sur chaque formulaire du système, ainsi qu'une description de chaque champ du formulaire. En plus d'être facile à utiliser, AEC Library peut générer des rapports instantanés en toute simplicité. Le logiciel a été conçu pour être flexible et convivial, répondant aux besoins des bibliothécaires et des spécialistes des médias.
      </p>
    </div>
    <div class="first">
      <h2 class="text-white">
        <strong>Fonctionnalités d'AEC Library</strong>
      </h2>
      <p>
        <i class="far fa-hand-point-right"></i> Permet de stocker divers types de documents : livres, journaux, magazines, revues,
        etc.<br>
        <i class="far fa-hand-point-right"></i> Organise les livres en fonction de leurs sujets.<br>
        <i class="far fa-hand-point-right"></i> Ajout facile de nouveaux livres.<br>
        <i class="far fa-hand-point-right"></i> Simplifie le processus de prêt des livres.<br>
        <i class="far fa-hand-point-right"></i> Le retour des livres est rapide et facile.<br>
        <i class="far fa-hand-point-right"></i> Calcul automatique des amendes pour les retards de retour.<br>
        <i class="far fa-hand-point-right"></i> Recherche d'un livre selon différents critères.<br>
        <i class="far fa-hand-point-right"></i> Affiche des données comme le nombre de livres disponibles, empruntés, ou de revues stockées.<br>
        <i class="far fa-hand-point-right"></i> Offre une méthode simple pour consulter le nombre de livres empruntés par un étudiant.
      </p>
    </div>


    <!-- </div> -->



    <br>
  </main>
  <!-- about content ended -->

  <!-- footer started -->

  <footer>

    <div class="footer-wrapper">

      <div class="footer-col">
        <h4 style="color: rgb(204, 204, 204);" class="address">Address</h4>
        <div class="content">
          <div class="place">
            <span class="fas fa-map-marker-alt" style="color: rgb(204, 204, 204);"></span>
            <span class="text" style="color: rgb(204, 204, 204);">Instituts Supérieurs des Etudes Technologiques de Bizerte</span>
          </div>
        </div>
        <div class="phone">
          <span class="fas fa-phone-alt" style="color: rgb(204, 204, 204);"></span>
          <span class="text" style="color: rgb(204, 204, 204);">+56202555</span>
        </div>
        <div class="email">
          <span class="fas fa-envelope" style="color: rgb(204, 204, 204);"></span>
          <a href="mailto:contact@example.com" class="text" style="color: rgb(204, 204, 204);">contact@example.com</a>
        </div>
      </div>
    </div>
    </div>
    <div class="icons">
      <ul>
        <li>
          <a href="#" title="LinkedIn" target="_blank" rel="noopener noreferrer" aria-label="Follow us on LinkedIn"><i class="fab fa-lg fa-linkedin-in icon"></i></a>
        </li>
        <li>
          <a href="#" title="GitHub" target="_blank" rel="noopener noreferrer" aria-label="Follow us on GitHub"> <i class="fab fa-lg fa-github icon"></i>
          </a>
        </li>
        <li>
          <a href="#" title="Twitter" target="_blank" rel="noopener noreferrer" aria-label="Follow us on Twitter"><i class="fab fa-lg fa-twitter icon"></i></a>
        </li>
        <li>
          <a href="#" title="YouTube" target="_blank" rel="noopener noreferrer" aria-label="Follow us on YouTube"><i class="fab fa-lg fa-youtube icon"></i></a>
        </li>
      </ul>
    </div>
    <div>
      <p style="color: rgb(204, 204, 204);">&#169 <span id="footer-year"></span> Copyright AEC Library</p>
    </div>
  </footer>


  <!-- footer ended -->

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="../assets/js/script.js"></script>
  <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
  <!-- Go to Top  -->

  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
  </script>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
  </script>
  <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
  <script>
    AOS.init({
      offset: 400, // offset (in px) from the original trigger point
      delay: 0, // values from 0 to 3000, with step 50ms
      duration: 1000 // values from 0 to 3000, with step 50ms
    });
  </script>

  <!-- <script>
    AOS.init({
      offset: 200,
      duration: 1000,
    });
  </script> -->
  <!-- Footer Year Calculator -->
  <script>
    var year = new Date().getFullYear();
    document.getElementById("footer-year").innerHTML = year;
  </script>
</body>

</html>