<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $title ?></title>
    <!-- ======= Styles ====== -->   
    <!-- fontawesome icons -->
    <script src="https://kit.fontawesome.com/ea12e32343.js" crossorigin="anonymous"></script>
</head>

<body>
    <!-- Partie dynamique -->
    <?php 
        include $template.'.phtml';
    ?>
</body>
</html>