<link rel="stylesheet" href="assets/css/styleFormAjoutAdhérent.css">

<form class="form" method="post" action="<?= $_SERVER['PHP_SELF'] ?>" enctype="multipart/form-data">
    <p class="title">Modifier Adhérent</p>
    <p class="message">Modifier un compte adhérent. </p>
    <input type="hidden" name="idAdherent" value="<?=$adherents['idAdherent']?>">
    
    <input type="hidden" name="idAdmin" id="" value="<?=$idAdmin?>">
    <div class="flex">
        <label>
            <input class="input" type="text" name="prenom" placeholder="" required="" value="<?= $adherents['prenom'] ?>">
            <span>Firstname</span>
        </label>

        <label>
            <input class="input" type="text" name="nom" placeholder="" required="" value="<?= $adherents['nom'] ?>">
            <span>Lastname</span>
        </label>
    </div>

    <label>
        <input class="input" type="email" name="email" placeholder="" required="" value="<?= $adherents['email'] ?>">
        <span>Email</span>
    </label>

    <label>
        <input class="input" type="tel" name="tel" placeholder="" required="" value="<?= $adherents['tel'] ?>">
        <span>Tel</span>
    </label>

    <label>
        <input class="input" type="password" name="password" placeholder="" required="" value="<?= $adherents['password'] ?>">
        <span>Password</span>
    </label>

    <div class="flex items-center justify-between mt-3">
        <label class="text-base font-medium text-gray-900">
            Profile Picture
        </label>
    </div>
    <div class="mt-2">
        <input type="hidden" name="current_picture" value="<?= $adherents['picture'] ?>">
        <input type="file" name="picture" />
    </div>

    <button class="submit">Update</button>
</form>
<div class="quiz-exit">
    <a href="DetailsAdherent.php?idAdmin=<?=$idAdmin?>"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" style="fill: #635147;">
            <path d="M21 11H6.414l5.293-5.293-1.414-1.414L2.586 12l7.707 7.707 1.414-1.414L6.414 13H21z"></path>
        </svg></a>
</div>
