<!DOCTYPE html>
<html lang="fr">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initialscale=1.0">
<title>Jeu de Quiz</title>
<link rel="stylesheet" href="stylequiz.css">
</head>
<body>
    <h1>Jeu de Quiz Javascript</h1>
    <div id="quiz">
        <p id="question"></p>
        <button class="reponse"></button>
        <button class="reponse"></button>
        <button class="reponse"></button>
        <button class="reponse"></button>
    </div>
    <div id="resultat"></div>
    <script src="quiz.js"></script>
</body>
</html>
