<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Jouer au Quiz</title>
    <!-- Quiz css  -->
    <!-- Bootstrap v4.3 -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />

    <!-- Font Awesome -->
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
      integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/"
      crossorigin="anonymous"
    />

    <link rel="icon" href=../assets/Favicons/8.webp>
    <title>A vous de Jouer</title>
    <link rel="stylesheet" href="../assets/css/Inscription.css">
    <link rel="stylesheet" href="css/style.css" />
  </head>
  <body>
    <!-- nav bar -->
    <div id="particles-js"></div>

    <nav class="navbar navbar-expand-lg navbar-dark bg-info">
      <a class="navbar-brand ml-4" href="../index2.php"
        ><img
          src="../img/finalLogo.webp"
          alt="AEC Library"
          class="logo-img"
      /></a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="../index2.php"
              ><i class="fas fa-home"></i> Acceuil
              <span class="sr-only">(current)</span></a
            >
          </li>
          <li class="nav-item">
            <a href="../QuiSommes-Nous.phtml" class="nav-link">
              <i class="fas fa-book"></i> Qui Sommes-Nous
            </a>
          </li>

          <li class="nav-item active">
            <a href="#" class="nav-link" onclick="return false;">
              <i class="fas fa-gamepad"></i> Play Quiz
            </a>
          </li>

          <li class="nav-item">
            <a href="../login.php" class="nav-link">
              <i class="fas fa-sign-in-alt"></i> Se connecter
            </a>
          </li>
          <li class="nav-item">
            <a href="../inscription.php" class="nav-link">
              <i class="fas fa-sign-in-alt"></i> Inscription
            </a>
          </li>
        </ul>
      </div>
    </nav>

    <div class="quiz-section" id="box" data-aos="fade">
      <img class="quiz-svg" src="quiz.svg" alt="" />
      <div class="quiz-main">
        <div class="quiz-text" style="color: white">
          Ennuyé ? Voici un petit quiz pour vous !
        </div>
        <!-- ***************** Game Page ***************** -->
        <a class="quiz-btn" href="pagequiz.phtml"
          >Jouer</a
        >
        <!-- ***************** Highscore Page ***************** -->

      </div>
      <img class="quiz-img" src="brain.webp" alt="" />
    </div>

    <!-- Footer  -->
    <footer>
      <div class="d-flex justify-content-between align-items-center">
        <div class="icons">
          <ul>
            <li>
              <a href="https://www.linkedin.com/in/sauravmukherjee44/"
                ><i class="fab fa-linkedin-in icon"></i
              ></a>
            </li>
            <li>
              <a href="https://github.com/SauravMukherjee44" target="github">
                <i class="fab fa-github icon"></i>
              </a>
            </li>
            <li>
              <a href="https://twitter.com/mesourav44"
                ><i class="fab fa-twitter icon"></i
              ></a>
            </li>
            <li>
              <a href="https://www.youtube.com/channel/UCYGVtIgQIAChKBWBmChxzJw"
                ><i class="fab fa-youtube icon"></i
              ></a>
            </li>
          </ul>
        </div>
        <div>
          <p>©2021 Copyright AEC Library</p>
        </div>
        <div>
          <p>
            <a href="" class="footer-text">Librarire AEC</a>
            &emsp;&emsp;
          </p>
        </div>
      </div>
    </footer>

    <!-- scripts -->
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    <script>
      window.onload = function () {
        document.getElementById("loading").style.display = "none";
        document.getElementById("container").style.display = "block";
      };
      particlesJS.load("particles-js", "../assets/js/config.json", function () {
        console.log("callback - particles.js config loaded");
      });
    </script>
  </body>
</html>
